### PR TITLE
Bug blitz  mantis 0004806

### PR DESCRIPTION
**Pull request by tudortimi**
This fixes [Mantis issue 0004806](http://www.eda.org/mantis/view.php?id=4806)

Note: This is more of an example pull request, seeing as how there doesn't seem to be consensus w.r.t. unmodeled fields within Accellera. The UVM user guide states that unmodeled fields are treated as RO fields which return 0 (the current behavior), but there's no mention of this in the standard (which is binding). The Mantis issue is, however, set to "priority immediate".

I recommend not pulling this change.

### CODE REVIEW

**Comment by krupan** [comment]
I just tried this out on my home machine and I'm having some trouble.  I downloaded the latest SVUnit (3.6) and it is looking for $SVUNIT_INSTALL//bin/cfg.mk and $SVUNIT_INSTALL/bin/questa.mk, which SVUnit 3.6 does not come with.  It seems we need to decide which version of SVUnit we are going to standarize on for this.

**Comment by tudortimi** [comment]
I use SVUnit 2.9 for this, since that's what I had installed. There is a point on the groups that says we need to decide on the SVUnit version. I guess taking the latest and greatest makes sense, as long as it's easy to set it up for multiple simulators (everybody is probably going to have his own).

**Comment by tudortimi** [comment]
I've added the old SVUnit Makefiles to the directory for now. It now works with SVUnit 3.6. I've changed the name to "Makefile.questa". If you want to run make, you should do a "ln -s Makefile.questa Makefile" and keep this local. This way each user can choose his/her sim.

**Comment by tudortimi** [comment]
Since the status of this issue is unclear (it might not be a bug but a feature) I'll close the pull request.

**Pull request closed without merging**
